
ETH_ADDRESS: "0x3998d7c68cbdc1df4a6936dba7429a825b4b1d2a.miner1"
ETH_POOL: "stratum+tcp://eu2.ethermine.org:4444"

CLAYMORE_DUAL_MODE: "no" 
CLAYMORE_MPORT: "4029"
CLAYMORE_ERES: "4"
CLAYMORE_ETHA: "2"
CLAYMORE_GSER: "1"
CLAYMORE_REBOOT_SCRIPT: "1"
CLAYMORE_ASM: "1"

GPU0_MCLOCK: "2070"
GPU0_CCLOCK: "1150"
GPU0_FANSPEED: "85"
GPU0_MAXTEMP: "75"
GPU0_DCRI: "4"

GPU1_MCLOCK: "2070"
GPU1_CCLOCK: "1150"
GPU1_FANSPEED: "85"
GPU1_MAXTEMP: "75"
GPU1_DCRI: "4"

GPU2_MCLOCK: "2070"
GPU2_CCLOCK: "1150"
GPU2_FANSPEED: "85"
GPU2_MAXTEMP: "75"
GPU2_DCRI: "4"

GPU3_MCLOCK: "2070"
GPU3_CCLOCK: "1150"
GPU3_FANSPEED: "85"
GPU3_MAXTEMP: "75"
GPU3_DCRI: "4"

GPU4_MCLOCK: "2070"
GPU4_CCLOCK: "1150"
GPU4_FANSPEED: "85"
GPU4_MAXTEMP: "75"
GPU4_DCRI: "4"

GPU5_MCLOCK: "2070"
GPU5_CCLOCK: "1150"
GPU5_FANSPEED: "85"
GPU5_MAXTEMP: "75"
GPU5_DCRI: "4"
